/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nesaridereservation;

import javax.swing.JOptionPane;

/**
 *
 * @author nabil
 */
public class HelpForm extends javax.swing.JFrame {

    /**
     * Creates new form HelpForm
     */
    public HelpForm() {
        initComponents();
        setTitle("Help");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_helplogin = new javax.swing.JLabel();
        lbl_helpregister = new javax.swing.JLabel();
        lbl_helphome = new javax.swing.JLabel();
        lbl_helpdriver = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_kembali = new javax.swing.JButton();
        lbl_keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Panduan Penggunaan Aplikasi");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GoLite Reservation");

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Help Center");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(031) 165172184");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("golite@gmail.com");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Our Social Media");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("@GoLite.official");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("0882009811994 (admin)");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel6))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel5))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel9))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(86, 86, 86)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_helplogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_helplogin.setForeground(new java.awt.Color(0, 153, 153));
        lbl_helplogin.setText("Panduan Penggunaan Menu Login Form");
        lbl_helplogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_helploginMouseClicked(evt);
            }
        });

        lbl_helpregister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_helpregister.setForeground(new java.awt.Color(0, 153, 153));
        lbl_helpregister.setText("Panduan Penggunaan Menu Register Form");
        lbl_helpregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_helpregisterMouseClicked(evt);
            }
        });

        lbl_helphome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_helphome.setForeground(new java.awt.Color(0, 153, 153));
        lbl_helphome.setText("Panduan Penggunaan Menu Penumpang Home Form");
        lbl_helphome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_helphomeMouseClicked(evt);
            }
        });

        lbl_helpdriver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_helpdriver.setForeground(new java.awt.Color(0, 153, 153));
        lbl_helpdriver.setText("Panduan Penggunaan Menu Driver Form");
        lbl_helpdriver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_helpdriverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_helpdriver)
                    .addComponent(lbl_helphome)
                    .addComponent(lbl_helpregister)
                    .addComponent(lbl_helplogin))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lbl_helplogin)
                .addGap(18, 18, 18)
                .addComponent(lbl_helpregister)
                .addGap(18, 18, 18)
                .addComponent(lbl_helphome)
                .addGap(18, 18, 18)
                .addComponent(lbl_helpdriver)
                .addGap(28, 28, 28))
        );

        jLabel7.setText("Apakah panduan di atas cukup membantu?  Jika tidak, silahkan hubungi Help Center");

        bt_kembali.setBackground(new java.awt.Color(0, 102, 102));
        bt_kembali.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_kembali.setForeground(new java.awt.Color(255, 255, 255));
        bt_kembali.setText("Kembali");
        bt_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_kembaliActionPerformed(evt);
            }
        });

        lbl_keluar.setBackground(new java.awt.Color(0, 102, 102));
        lbl_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_keluar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_keluar.setText("Keluar");
        lbl_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbl_keluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_kembali)
                            .addComponent(lbl_keluar))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_helploginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_helploginMouseClicked
        String pesan = "<html>"
        + "<b>Langkah-langkah Penggunaan</b><br><br>"
        + "1. Pada menu Login Form, user diharapkan sudah memiliki akun Nesa Ride Reservation.<br>"
        + "   Jika belum memiliki akun, terdapat menu register yang akan menuju ke Register Form<br><br>"
        + "2. Apabila sudah memiliki akun, silahkan masukkan Username dan Password akun Anda. Lalu login<br><br>"
        + "3. Sebelum Anda menekan tombol login, terdapat pilihan (Penumpang dan Driver).<br>"
        + "   Jika Anda memilih Penumpang, Anda akan masuk ke menu Penumpang. Jika Anda memilih Driver,<br>"
        + "   Anda akan masuk ke menu Driver.";

        JOptionPane.showMessageDialog(this, pesan, "Panduan Penggunaan Menu Login Form" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lbl_helploginMouseClicked

    private void lbl_helpregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_helpregisterMouseClicked
        String pesan = "<html>"
        + "<b>Langkah-langkah Penggunaan</b><br><br>"
        + "1. Menu ini dibuat untuk user ketika belum memiliki akun,<br>"
        + "   dan akan membuat akun pada menu ini.<br><br>"
        + "2. Pada pembuatan akun memerlukan data user yang akan dimasukkan<br>"
        + "   pada kolom input data.<br><br>"
        + "3. Masukkan data Anda yang terdiri dari Nama, Email, Nomor Telepon,<br>"
        + "   Username, Password, dan Repassword (Confirm Password).<br><br>"
        + "4. Maka secara otomatis data Anda akan tersimpan dan digunakan untuk<br>"
        + "   login selanjutnya.<br><br>"
        + "5. Pada Register Form terdapat menu yang menuju ke login jika Anda sudah<br>"
        + "   membuat akun sebelumnya, dengan menekan text (masuk).<br><br>";
        
        JOptionPane.showMessageDialog(this, pesan, "Panduan Penggunaan Menu Register Form" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lbl_helpregisterMouseClicked

    private void lbl_helphomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_helphomeMouseClicked
        String pesan = "<html>"
        + "<b>Langkah-langkah Penggunaan</b><br><br>"
        + "1. Menu ini dibuat untuk user sebagai Penumpang yang akan<br>"
        + "   melakukan pemesanan.<br><br>"
        + "2. Ketika Penumpang akan melakukan pemesanan , maka langkah<br>"
        + "   yang pertama adalah mengisi kolom data Penumpang yaitu<br>"
        + "   nama Penumpang, Kemudian Nomor Telepon, lalu memilih Driver.<br><br>"
        + "3. Setelah Anda memasukkan data Penumpang, Anda diminta memilih<br>"
        + "   lokasi yang akan dituju.<br><br>"
        + "4. Kemudian Anda diminta memilih moda transportasi yang akan<br>"
        + "   digunakan sesuai dengan kebutuhan Anda, lalu tarif<br>"
        + "   akan otomatis muncul sesuai dengan lokasi yang Anda pilih.<br><br>"
        + "5. Setelah memilih moda transportasi, kemudian Anda diminta<br>"
        + "   untuk memasukkan jumlah beli sesuai dengan kebutuhan Anda.<br>"
        + "   Maka otomatis akan muncul total harga.<br><br>"
        + "6. Setelah memasukkan jumlah beli, Anda diminta untuk memasukan<br>"
        + "   nominal bayar, maka otomatis akan muncul nominal kembalian.<br><br>"
        + "7. Setelah pembuatan pesanan selesai, Anda diminta untuk Submit<br>"
        + "   pesanan agar pesanan segera terkonfirmasi oleh Driver.<br><br>"
        + "8. Tunggu hingga Driver menghubungi Anda.";
        
        JOptionPane.showMessageDialog(this, pesan, "Panduan Penggunaan Menu Penumpang Home Form" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lbl_helphomeMouseClicked

    private void lbl_helpdriverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_helpdriverMouseClicked
        String pesan = "<html>"
        + "<b>Langkah-langkah Penggunaan</b><br><br>"
        + "1. Menu ini dibuat untuk user sebagai Driver yang akan<br>"
        + "   mengambil pesanan.<br><br>"
        + "2. Menu ini juga menampilkan hasil pemesanan dari Penumpang<br>"
        + "   yang telah membuat pesanan pada tabel.<br><br>"
        + "3. Driver dapat melihat hasil pemesanan, kemudian Driver dapat<br>"
        + "   menghubungi Nomor Telepon Penumpang dari data yang ditampilkan.<br><br>"
        + "4. Selain itu, Driver dapat mencetak pesanan pada kolom Cetak, <br>"
        + "   kemudian hasil cetak pesanan akan muncul berupa laporan pesanan.<br><br>"
        + "5. Apabila Driver telah menyelesaikan pesanan, Driver dapat menghapus<br>"
        + "   pesanan dengan menekan tombol hapus.";
        
        JOptionPane.showMessageDialog(this, pesan, "Panduan Penggunaan Menu Driver Form" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_lbl_helpdriverMouseClicked

    private void bt_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_kembaliActionPerformed
        
        int answer = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin kembali ke menu Login?", "Kembali", JOptionPane.OK_OPTION);
        if(answer == JOptionPane.OK_OPTION){
            dispose();
        
        
        LoginForm lg = new LoginForm();
        HelpForm hf = new HelpForm();
        lg.setVisible(true);
        this.setVisible(false);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(HelpForm.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_bt_kembaliActionPerformed

    private void lbl_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbl_keluarActionPerformed
        
        int answer = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Keluar", JOptionPane.OK_OPTION);
        if(answer == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_lbl_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbl_helpdriver;
    private javax.swing.JLabel lbl_helphome;
    private javax.swing.JLabel lbl_helplogin;
    private javax.swing.JLabel lbl_helpregister;
    private javax.swing.JButton lbl_keluar;
    // End of variables declaration//GEN-END:variables
}
