/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nesaridereservation;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public LoginForm() {
        initComponents();
        setTitle("Login Form");
        
        con = Database.mycon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_log_username = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        pf_log_password = new javax.swing.JPasswordField();
        rb_penumpang = new javax.swing.JRadioButton();
        rb_driver = new javax.swing.JRadioButton();
        bt_log_login = new javax.swing.JButton();
        bt_log_keluar = new javax.swing.JButton();
        lbl_register1 = new javax.swing.JLabel();
        lbl_register2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Login Form");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("GoLite Reservation");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/250.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Username");

        txt_log_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_log_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_log_username.setToolTipText("");
        jScrollPane1.setViewportView(txt_log_username);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Password  ");

        pf_log_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pf_log_password.setText("jPasswordField1");
        pf_log_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pf_log_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_log_passwordActionPerformed(evt);
            }
        });

        rb_penumpang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_penumpang.setText("Penumpang");
        rb_penumpang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_penumpangActionPerformed(evt);
            }
        });

        rb_driver.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rb_driver.setText("Driver");
        rb_driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_driverActionPerformed(evt);
            }
        });

        bt_log_login.setBackground(new java.awt.Color(0, 153, 153));
        bt_log_login.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_log_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_log_login.setText("Login");
        bt_log_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_log_loginActionPerformed(evt);
            }
        });

        bt_log_keluar.setBackground(new java.awt.Color(0, 153, 153));
        bt_log_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_log_keluar.setForeground(new java.awt.Color(255, 255, 255));
        bt_log_keluar.setText("Keluar");
        bt_log_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_log_keluarActionPerformed(evt);
            }
        });

        lbl_register1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_register1.setForeground(new java.awt.Color(0, 153, 153));
        lbl_register1.setText("Daftar");
        lbl_register1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_register1MouseClicked(evt);
            }
        });

        lbl_register2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_register2.setText("Belum mempunyai Akun?");
        lbl_register2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_register2MouseClicked(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("About Us");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Help");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(92, 92, 92))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(70, 70, 70))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(jLabel2)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_log_password, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(rb_penumpang)
                                            .addGap(19, 19, 19)
                                            .addComponent(rb_driver))
                                        .addComponent(bt_log_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_register2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_log_keluar)
                                    .addComponent(lbl_register1))))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(pf_log_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_penumpang)
                    .addComponent(rb_driver))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_log_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_log_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_register1)
                    .addComponent(lbl_register2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(0, 23, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf_log_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_log_passwordActionPerformed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_pf_log_passwordActionPerformed

         
    private void bt_log_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_log_loginActionPerformed
        // Masuk ke menu order
        
        String un = txt_log_username.getText();
        String ps = pf_log_password.getText();
        
        try {
            
            String sql = " SELECT * FROM daftar WHERE Username=? AND Password=?";
            pst = con.prepareCall(sql);
            
            pst.setString(1, un); // Username 
            pst.setString(2, ps); // Password
            
            rs = pst.executeQuery();
            
            if(rs.next()){ // Jika benar akan melakukan ini
                
                JOptionPane.showMessageDialog(rootPane, "Berhasil login");
                
                // Masuk ke menu Home
                if(rb_penumpang.isSelected()){
                    HomeForm hm = new HomeForm();
                    LoginForm lg = new LoginForm();
                    hm.setVisible(true);
                    this.setVisible(false);
                    hm.pack();
                    hm.setLocationRelativeTo(null);
                    hm.setDefaultCloseOperation(LoginForm.EXIT_ON_CLOSE);
                }
                
                if(rb_driver.isSelected()){
                    DriverForm dv = new DriverForm();
                    LoginForm lg = new LoginForm();
                    dv.setVisible(true);
                    this.setVisible(false);
                    dv.pack();
                    dv. setLocationRelativeTo(null);
                    dv.setDefaultCloseOperation(LoginForm.EXIT_ON_CLOSE);
                }
                
            }else{ // Jika salah akan melakukan ini
                
                JOptionPane.showMessageDialog(rootPane, "Login gagal, Akun invalid");
                
            }
            
        } catch (Exception e) {
        }
 
    }//GEN-LAST:event_bt_log_loginActionPerformed

    private void bt_log_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_log_keluarActionPerformed
        // Memberikan pilihan ingin keluar atau tetap pada menu Login
        
        int answer = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Keluar", JOptionPane.OK_OPTION);
        if(answer == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_bt_log_keluarActionPerformed

    private void rb_penumpangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_penumpangActionPerformed
              
    }//GEN-LAST:event_rb_penumpangActionPerformed

    private void rb_driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_driverActionPerformed
        
    }//GEN-LAST:event_rb_driverActionPerformed

    private void lbl_register1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_register1MouseClicked
        
        RegisterForm rg = new RegisterForm();
        LoginForm lg = new LoginForm();
        rg.setVisible(true);
        this.setVisible(false);
        rg.pack();
        rg.setLocationRelativeTo(null);
        rg.setDefaultCloseOperation(LoginForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_lbl_register1MouseClicked

    private void lbl_register2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_register2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_register2MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        String pesan = "<html>"
        + "Nesa Ride Reservation adalah aplikasi antar jemput yang dikelola Mahasiswa Unesa <br>"
        + "dan untuk Mahasiswa Unesa. Program ini pada awalnya belum memiliki aplikasi dan <br>"
        + "masih menggunakan media sosial Whatsapp sebagai sistem pemesanan, lalu dari kondisi<br>"
        + "tersebut kami melihat peluang untuk membuat aplikasi Nesa Ride ini agar sistem <br>"
        + "pemesanannya lebih efektif dan efisien. Aplikasi ini berfungsi seperti halnya <br>"
        + "aplikasi ojek online pada umumnya, akan tetapi jika melihat desainnya bisa dikatakan <br>"
        + " sederhana. Aplikasi ini dapat diakses user sebagai penumpang dan driver menggunakan akun. <br><br>"
                
        + "<b>Contact Person and Customer Service</b><br>" + "Email : achmadkhoirun1927@gmail.com <br>" + "Telepon : 081332440129 <br><br>"
        + "<b>Team Developer (NamevGroup)</b><br>" + "Muhammed Nabil Ghulam Marzouk Nour El Ein<br>" + "Achmad Khoirun Niam Aljunaidi<br>" + "Evan Rasyid Nandana Iswara<br><br>"
        + "<b>Created Using</b><br>" + "by Java with Apache Netbeans IDE<br><br>"
        + "<b>Version</b><br>" + "1.03.524";

        JOptionPane.showMessageDialog(this, pesan, "About Us" , JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        HelpForm hf = new HelpForm();
        LoginForm lg = new LoginForm();
        hf.setVisible(true);
        this.setVisible(false);
        hf.pack();
        hf.setLocationRelativeTo(null);
        hf.setDefaultCloseOperation(LoginForm.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_log_keluar;
    private javax.swing.JButton bt_log_login;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_register1;
    private javax.swing.JLabel lbl_register2;
    private javax.swing.JPasswordField pf_log_password;
    private javax.swing.JRadioButton rb_driver;
    private javax.swing.JRadioButton rb_penumpang;
    private javax.swing.JTextPane txt_log_username;
    // End of variables declaration//GEN-END:variables
}
