/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nesaridereservation;

import java.sql.Statement;
import javax.swing.JOptionPane;


public class RegisterForm extends javax.swing.JFrame {

    public static String nama;
    public static String username;
    public static String email;
    public static String telepon;
    public static String password;
    
    public RegisterForm() {
        initComponents();
        
        setTitle("Register Form");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_reg_email = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_reg_telepon = new javax.swing.JTextPane();
        pf_reg_password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txt_reg_username = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_reg_nama = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        lbl_regtolog = new javax.swing.JLabel();
        bt_reg_register = new javax.swing.JButton();
        bt_reg_keluar = new javax.swing.JButton();
        pf_reg_repassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/100.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -60, 230, 230));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jLabel1.setText("Register Form");

        txt_reg_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txt_reg_email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_reg_email.setForeground(new java.awt.Color(153, 153, 153));
        txt_reg_email.setText("Email");
        jScrollPane8.setViewportView(txt_reg_email);

        txt_reg_telepon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txt_reg_telepon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_reg_telepon.setForeground(new java.awt.Color(153, 153, 153));
        txt_reg_telepon.setText("Telepon");
        jScrollPane7.setViewportView(txt_reg_telepon);

        pf_reg_password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pf_reg_password.setText("Password");
        pf_reg_password.setToolTipText("");
        pf_reg_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pf_reg_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_reg_passwordActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Create your Password");

        txt_reg_username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txt_reg_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_reg_username.setForeground(new java.awt.Color(153, 153, 153));
        txt_reg_username.setText("Username");
        jScrollPane9.setViewportView(txt_reg_username);

        txt_reg_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txt_reg_nama.setContentType(""); // NOI18N
        txt_reg_nama.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_reg_nama.setForeground(new java.awt.Color(153, 153, 153));
        txt_reg_nama.setText("Nama");
        jScrollPane6.setViewportView(txt_reg_nama);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setText("GoLite Reservation");

        lbl_regtolog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl_regtolog.setForeground(new java.awt.Color(0, 153, 153));
        lbl_regtolog.setText("Masuk");
        lbl_regtolog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_regtologMouseClicked(evt);
            }
        });

        bt_reg_register.setBackground(new java.awt.Color(0, 153, 153));
        bt_reg_register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_reg_register.setForeground(new java.awt.Color(255, 255, 255));
        bt_reg_register.setText("Register");
        bt_reg_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reg_registerActionPerformed(evt);
            }
        });

        bt_reg_keluar.setBackground(new java.awt.Color(0, 153, 153));
        bt_reg_keluar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bt_reg_keluar.setForeground(new java.awt.Color(255, 255, 255));
        bt_reg_keluar.setText("Keluar");
        bt_reg_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_reg_keluarActionPerformed(evt);
            }
        });

        pf_reg_repassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pf_reg_repassword.setText("Repassword");
        pf_reg_repassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        pf_reg_repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_reg_repasswordActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Repassword");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Sudah mempunyai Akun?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(pf_reg_password, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(pf_reg_repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_regtolog))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bt_reg_register, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_reg_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_reg_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pf_reg_repassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_reg_register, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_reg_keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_regtolog)
                    .addComponent(jLabel4))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 340, 600));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 97, -1, 270));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pf_reg_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_reg_passwordActionPerformed
        
    }//GEN-LAST:event_pf_reg_passwordActionPerformed

    private void bt_reg_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reg_keluarActionPerformed
        // Memberikan pilihan ingin keluar atau tetap pada menu Register
        
        int answer = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Keluar", JOptionPane.OK_OPTION);
        if(answer == JOptionPane.OK_OPTION){
            dispose();
        }
    }//GEN-LAST:event_bt_reg_keluarActionPerformed

    private void bt_reg_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_reg_registerActionPerformed
        // Register akun lalu masuk ke menu login
        
        String nama = txt_reg_nama.getText();
        String username = txt_reg_username.getText();
        String email = txt_reg_email.getText();
        String telepon = txt_reg_telepon.getText();
        String password = pf_reg_password.getText();
        String repassword = pf_reg_repassword.getText();
        
        if(password.equals(repassword)){
            
        try {
            
            Statement st = Database.mycon().createStatement();
            st.executeUpdate(" INSERT INTO daftar (Nama,Username,Email,Nomer,Password)"
                    + "VALUES ('"+nama+"','"+username+"','"+email+"','"+telepon+"','"+password+"') ");
            
            JOptionPane.showMessageDialog(rootPane, "Berhasil membuat Akun, Siilahkan Login");
            
            LoginForm lg = new LoginForm();
        RegisterForm rg = new RegisterForm();
        lg.setVisible(true);
        this.setVisible(false);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(RegisterForm.EXIT_ON_CLOSE);
            
        } catch (Exception e) {
            System.out.println(e);
        }
        
        }else {
            
            JOptionPane.showMessageDialog(rootPane, "Password Anda tidak sama! Mohon masukkan ulang");
        }
        
    }//GEN-LAST:event_bt_reg_registerActionPerformed

    private void lbl_regtologMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_regtologMouseClicked
        // Masuk ke menu Login (Karena sudah memiliki akun)
        LoginForm lg = new LoginForm();
        RegisterForm rg = new RegisterForm();
        lg.setVisible(true);
        this.setVisible(false);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(RegisterForm.EXIT_ON_CLOSE);
    }//GEN-LAST:event_lbl_regtologMouseClicked

    private void pf_reg_repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_reg_repasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_reg_repasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_reg_keluar;
    private javax.swing.JButton bt_reg_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lbl_regtolog;
    private javax.swing.JPasswordField pf_reg_password;
    private javax.swing.JPasswordField pf_reg_repassword;
    private javax.swing.JTextPane txt_reg_email;
    private javax.swing.JTextPane txt_reg_nama;
    private javax.swing.JTextPane txt_reg_telepon;
    private javax.swing.JTextPane txt_reg_username;
    // End of variables declaration//GEN-END:variables

    
}
