libs.absolutelayout.classpath=\
    ${base}/absolutelayout/AbsoluteLayout.jar
libs.absolutelayout.displayName=Absolute Layout
libs.CopyLibs.classpath=\
    ${base}/CopyLibs/org-netbeans-modules-java-j2seproject-copylibstask.jar
libs.CopyLibs.displayName=CopyLibs Task
libs.CopyLibs.prop-version=3.0
libs.MySQL_Connector.classpath=\
    
libs.MySQL_Connector.displayName=MySQL Connector
libs.MySQL_Connector_JDBC.classpath=\
    ${base}/MySQL_Connector_JDBC/mysql-connector-j-9.3.0.zip
libs.MySQL_Connector_JDBC.displayName=MySQL Connector JDBC
